name: Release Alpha and Propose Stable

on:
  pull_request:
    types: [closed]
    branches: [dev]

jobs:
  publish_alpha:
    uses: OpenVoiceOS/gh-automations/.github/workflows/publish-alpha.yml@dev
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      MATRIX_TOKEN: ${{ secrets.MATRIX_TOKEN }}
    with:
      branch: 'dev'
      base_branch: 'master'
      version_file: 'hivemind_sqlite_database/version.py'
      update_changelog: true
      publish_prerelease: true
      changelog_max_issues: 100
      publish_pypi: true
      propose_release: true
      notify_matrix: true
      matrix_channel: '!jImYhOcJWVpvCRsDjc:matrix.org'
